# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExportWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(467, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ExportDataPath = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ExportDataPath.sizePolicy().hasHeightForWidth())
        self.ExportDataPath.setSizePolicy(sizePolicy)
        self.ExportDataPath.setMaximumSize(QtCore.QSize(300, 50))
        self.ExportDataPath.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:  rgb(0,0,0);\n"
"\n"
"font: 14pt \"Book Antiqua\";")
        self.ExportDataPath.setObjectName("ExportDataPath")
        self.horizontalLayout.addWidget(self.ExportDataPath)
        self.ExportDatabtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExportDatabtn.sizePolicy().hasHeightForWidth())
        self.ExportDatabtn.setSizePolicy(sizePolicy)
        self.ExportDatabtn.setMaximumSize(QtCore.QSize(50, 50))
        self.ExportDatabtn.setStyleSheet("QPushButton{\n"
"border-image:url(:/icons/icons/folder.png)\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(111, 111, 111);\n"
"}")
        self.ExportDatabtn.setText("")
        self.ExportDatabtn.setObjectName("ExportDatabtn")
        self.horizontalLayout.addWidget(self.ExportDatabtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ExportDataPath_2 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExportDataPath_2.sizePolicy().hasHeightForWidth())
        self.ExportDataPath_2.setSizePolicy(sizePolicy)
        self.ExportDataPath_2.setMaximumSize(QtCore.QSize(300, 50))
        self.ExportDataPath_2.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:  rgb(0,0,0);\n"
"\n"
"font: 14pt \"Book Antiqua\";")
        self.ExportDataPath_2.setObjectName("ExportDataPath_2")
        self.horizontalLayout_2.addWidget(self.ExportDataPath_2)
        self.ExportDatabtn_2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExportDatabtn_2.sizePolicy().hasHeightForWidth())
        self.ExportDatabtn_2.setSizePolicy(sizePolicy)
        self.ExportDatabtn_2.setMaximumSize(QtCore.QSize(50, 50))
        self.ExportDatabtn_2.setStyleSheet("QPushButton{\n"
"border-image:url(:/icons/icons/folder.png)\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(111, 111, 111);\n"
"}")
        self.ExportDatabtn_2.setText("")
        self.ExportDatabtn_2.setObjectName("ExportDatabtn_2")
        self.horizontalLayout_2.addWidget(self.ExportDatabtn_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.exportbtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportbtn.sizePolicy().hasHeightForWidth())
        self.exportbtn.setSizePolicy(sizePolicy)
        self.exportbtn.setObjectName("exportbtn")
        self.verticalLayout_2.addWidget(self.exportbtn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMaximumSize(QtCore.QSize(900, 500))
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout.addWidget(self.treeWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ExportDataPath.setPlaceholderText(_translate("Form", "请输入导出数据地址"))
        self.ExportDataPath_2.setPlaceholderText(_translate("Form", "请输入导出热图地址"))
        self.exportbtn.setText(_translate("Form", "导出"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "1"))
import src_rc
