# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1245, 807)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(20, 10, 1221, 791))
        self.background.setStyleSheet("background-color: rgb(15, 79, 255);\n"
"border-radius:30px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(140, 60, 1081, 731))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.select_page = QtWidgets.QWidget()
        self.select_page.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.select_page.setObjectName("select_page")
        self.frame = QtWidgets.QFrame(self.select_page)
        self.frame.setGeometry(QtCore.QRect(210, 50, 351, 391))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255 );")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.back1 = QtWidgets.QLabel(self.frame)
        self.back1.setGeometry(QtCore.QRect(0, 0, 351, 391))
        self.back1.setStyleSheet("border-image: url(:/images/images/bd8e86e001cf58355839038e3d3b9918.jpeg);\n"
"border-radius:20px;")
        self.back1.setText("")
        self.back1.setObjectName("back1")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 291, 151))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"color:rgb(255,255,255);\n"
"font: 32pt \"Bodoni MT\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 210, 351, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(100, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.peptidebtn = QtWidgets.QPushButton(self.frame)
        self.peptidebtn.setGeometry(QtCore.QRect(0, 0, 351, 391))
        self.peptidebtn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgba(213, 213, 227,100);\n"
"}")
        self.peptidebtn.setText("")
        self.peptidebtn.setObjectName("peptidebtn")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 241, 101))
        self.label_5.setStyleSheet("font: 16pt \"Bahnschrift SemiLight SemiConde\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.back1.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.line.raise_()
        self.peptidebtn.raise_()
        self.frame_2 = QtWidgets.QFrame(self.select_page)
        self.frame_2.setGeometry(QtCore.QRect(600, 50, 351, 391))
        self.frame_2.setStyleSheet("background-color: rgba(255, 255, 255 );")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.back1_2 = QtWidgets.QLabel(self.frame_2)
        self.back1_2.setGeometry(QtCore.QRect(0, 0, 351, 391))
        self.back1_2.setStyleSheet("border-image: url(:/images/images/8316e2f5c2d9fa8f91fef23f32e2bb8e.jpeg);\n"
"border-radius:20px;")
        self.back1_2.setText("")
        self.back1_2.setObjectName("back1_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 291, 151))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"color:rgb(255,255,255);\n"
"font: 32pt \"Bodoni MT\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(0, 210, 351, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(100, 0))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tcrbtn = QtWidgets.QPushButton(self.frame_2)
        self.tcrbtn.setGeometry(QtCore.QRect(0, 0, 351, 391))
        self.tcrbtn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgba(213, 213, 227,100);\n"
"}")
        self.tcrbtn.setText("")
        self.tcrbtn.setObjectName("tcrbtn")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 241, 101))
        self.label_6.setStyleSheet("font: 16pt \"Bahnschrift SemiLight SemiConde\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.back1_2.raise_()
        self.label_6.raise_()
        self.label_3.raise_()
        self.line_2.raise_()
        self.tcrbtn.raise_()
        self.frame_3 = QtWidgets.QFrame(self.select_page)
        self.frame_3.setGeometry(QtCore.QRect(210, 460, 751, 251))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(0, 0, 741, 241))
        self.label.setStyleSheet("border-image: url(:/images/images/27cb292809cc8cf7b10e728a3ee0fd0d.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 391, 121))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 32pt \"Bodoni MT\";")
        self.label_4.setObjectName("label_4")
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setGeometry(QtCore.QRect(0, 140, 741, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.aompbtn = QtWidgets.QPushButton(self.frame_3)
        self.aompbtn.setGeometry(QtCore.QRect(0, 0, 741, 241))
        self.aompbtn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgba(213, 213, 227,100);\n"
"}")
        self.aompbtn.setText("")
        self.aompbtn.setObjectName("aompbtn")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 461, 61))
        self.label_7.setStyleSheet("font: 16pt \"Bahnschrift SemiLight SemiConde\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label.raise_()
        self.label_7.raise_()
        self.label_4.raise_()
        self.line_3.raise_()
        self.aompbtn.raise_()
        self.stackedWidget.addWidget(self.select_page)
        self.peptide_page = QtWidgets.QWidget()
        self.peptide_page.setStyleSheet("background-color:rgb(117, 139, 173);\n"
"border-radius:20px;")
        self.peptide_page.setObjectName("peptide_page")
        self.inputHLA1 = QtWidgets.QLineEdit(self.peptide_page)
        self.inputHLA1.setGeometry(QtCore.QRect(30, 30, 301, 61))
        self.inputHLA1.setStyleSheet("QLineEdit{\n"
"background-color: rgba(255, 255, 255,150);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgb(0,0,0);\n"
"font: 25 16pt \"Bahnschrift Light\";\n"
"}\n"
"")
        self.inputHLA1.setObjectName("inputHLA1")
        self.inputPeptide = QtWidgets.QLineEdit(self.peptide_page)
        self.inputPeptide.setGeometry(QtCore.QRect(430, 30, 291, 61))
        self.inputPeptide.setStyleSheet("QLineEdit{\n"
"background-color: rgba(255, 255, 255,150);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgb(0,0,0);\n"
"font: 25 16pt \"Bahnschrift Light\";\n"
"}")
        self.inputPeptide.setObjectName("inputPeptide")
        self.peptideresult = QtWidgets.QTableWidget(self.peptide_page)
        self.peptideresult.setGeometry(QtCore.QRect(20, 120, 491, 581))
        self.peptideresult.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.peptideresult.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.peptideresult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.peptideresult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.peptideresult.setRowCount(0)
        self.peptideresult.setObjectName("peptideresult")
        self.peptideresult.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.peptideresult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peptideresult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peptideresult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peptideresult.setHorizontalHeaderItem(3, item)
        self.predictPeptide = QtWidgets.QPushButton(self.peptide_page)
        self.predictPeptide.setGeometry(QtCore.QRect(840, 30, 61, 61))
        self.predictPeptide.setStyleSheet("QWidget{\n"
"    border-image: url(:/icons/icons/analysis.png);\n"
"    \n"
"    background-color: rgb(255, 154, 114);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.predictPeptide.setText("")
        self.predictPeptide.setObjectName("predictPeptide")
        self.peptideprogress = QtWidgets.QProgressBar(self.peptide_page)
        self.peptideprogress.setGeometry(QtCore.QRect(0, 710, 1081, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peptideprogress.sizePolicy().hasHeightForWidth())
        self.peptideprogress.setSizePolicy(sizePolicy)
        self.peptideprogress.setMaximumSize(QtCore.QSize(16777215, 21))
        self.peptideprogress.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255,0);")
        self.peptideprogress.setProperty("value", 0)
        self.peptideprogress.setObjectName("peptideprogress")
        self.peptideExport = QtWidgets.QPushButton(self.peptide_page)
        self.peptideExport.setGeometry(QtCore.QRect(920, 30, 61, 61))
        self.peptideExport.setStyleSheet("QWidget{\n"
"    \n"
"    border-image: url(:/icons/icons/save.png);\n"
"    background-color:rgb(92, 233, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.peptideExport.setText("")
        self.peptideExport.setObjectName("peptideExport")
        self.peptideRefresh = QtWidgets.QPushButton(self.peptide_page)
        self.peptideRefresh.setGeometry(QtCore.QRect(1000, 30, 61, 61))
        self.peptideRefresh.setStyleSheet("QWidget{\n"
"    border-image:url(:/icons/icons/清除_clear.png);\n"
"    background-color: rgb(161, 255, 73);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.peptideRefresh.setText("")
        self.peptideRefresh.setObjectName("peptideRefresh")
        self.peptideGraphArea = QtWidgets.QScrollArea(self.peptide_page)
        self.peptideGraphArea.setGeometry(QtCore.QRect(580, 110, 491, 601))
        self.peptideGraphArea.setStyleSheet("QWidget{\n"
"    background-color: rgba(27, 53, 113,255);\n"
"    border-radius:20px;\n"
"}")
        self.peptideGraphArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.peptideGraphArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.peptideGraphArea.setWidgetResizable(True)
        self.peptideGraphArea.setObjectName("peptideGraphArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 491, 601))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.peptideGraphArea.setWidget(self.scrollAreaWidgetContents)
        self.peptide_result_back = QtWidgets.QLabel(self.peptide_page)
        self.peptide_result_back.setGeometry(QtCore.QRect(10, 110, 551, 601))
        self.peptide_result_back.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.peptide_result_back.setText("")
        self.peptide_result_back.setObjectName("peptide_result_back")
        self.peptide_hla_folderbtn = QtWidgets.QPushButton(self.peptide_page)
        self.peptide_hla_folderbtn.setGeometry(QtCore.QRect(340, 30, 61, 61))
        self.peptide_hla_folderbtn.setStyleSheet("QPushButton{\n"
"image: url(:/icons/icons/folder.png);\n"
"    \n"
"    background-color: rgb(255, 242, 64);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.peptide_hla_folderbtn.setText("")
        self.peptide_hla_folderbtn.setObjectName("peptide_hla_folderbtn")
        self.peptide_peptide_folderbtn = QtWidgets.QPushButton(self.peptide_page)
        self.peptide_peptide_folderbtn.setGeometry(QtCore.QRect(730, 30, 61, 61))
        self.peptide_peptide_folderbtn.setStyleSheet("QPushButton{\n"
"image: url(:/icons/icons/folder.png);\n"
"background-color: rgb(255, 242, 64);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.peptide_peptide_folderbtn.setText("")
        self.peptide_peptide_folderbtn.setObjectName("peptide_peptide_folderbtn")
        self.peptide_append = QtWidgets.QCheckBox(self.peptide_page)
        self.peptide_append.setGeometry(QtCore.QRect(840, 90, 81, 16))
        self.peptide_append.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.peptide_append.setObjectName("peptide_append")
        self.peptide_result_back.raise_()
        self.inputHLA1.raise_()
        self.inputPeptide.raise_()
        self.predictPeptide.raise_()
        self.peptideprogress.raise_()
        self.peptideExport.raise_()
        self.peptideRefresh.raise_()
        self.peptideGraphArea.raise_()
        self.peptide_hla_folderbtn.raise_()
        self.peptide_peptide_folderbtn.raise_()
        self.peptide_append.raise_()
        self.peptideresult.raise_()
        self.stackedWidget.addWidget(self.peptide_page)
        self.tcr_page = QtWidgets.QWidget()
        self.tcr_page.setStyleSheet("background-color:rgb(117, 139, 173);\n"
"border-radius:20px;")
        self.tcr_page.setObjectName("tcr_page")
        self.inputHLA2 = QtWidgets.QLineEdit(self.tcr_page)
        self.inputHLA2.setGeometry(QtCore.QRect(30, 30, 301, 61))
        self.inputHLA2.setStyleSheet("QLineEdit{\n"
"background-color: rgba(255, 255, 255,150);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgb(0,0,0);\n"
"font: 25 16pt \"Bahnschrift Light\";\n"
"}\n"
"")
        self.inputHLA2.setObjectName("inputHLA2")
        self.inputTcr = QtWidgets.QLineEdit(self.tcr_page)
        self.inputTcr.setGeometry(QtCore.QRect(430, 30, 291, 61))
        self.inputTcr.setStyleSheet("QLineEdit{\n"
"background-color: rgba(255, 255, 255,150);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgb(0,0,0);\n"
"font: 25 16pt \"Bahnschrift Light\";\n"
"}")
        self.inputTcr.setObjectName("inputTcr")
        self.predictTcr = QtWidgets.QPushButton(self.tcr_page)
        self.predictTcr.setGeometry(QtCore.QRect(840, 30, 61, 61))
        self.predictTcr.setStyleSheet("QWidget{\n"
"border-image: url(:/icons/icons/analysis.png);\n"
"background-color: rgb(255, 154, 114);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.predictTcr.setText("")
        self.predictTcr.setObjectName("predictTcr")
        self.tcrGraphArea = QtWidgets.QScrollArea(self.tcr_page)
        self.tcrGraphArea.setGeometry(QtCore.QRect(580, 110, 491, 601))
        self.tcrGraphArea.setStyleSheet("background-color: rgba(27, 53, 113,255);\n"
"border-radius:20px;")
        self.tcrGraphArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tcrGraphArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tcrGraphArea.setWidgetResizable(True)
        self.tcrGraphArea.setObjectName("tcrGraphArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 491, 601))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.tcrGraphArea.setWidget(self.scrollAreaWidgetContents_2)
        self.tcrRefresh = QtWidgets.QPushButton(self.tcr_page)
        self.tcrRefresh.setGeometry(QtCore.QRect(1000, 30, 61, 61))
        self.tcrRefresh.setStyleSheet("QWidget{\n"
"    border-image:url(:/icons/icons/清除_clear.png);\n"
"background-color: rgb(161, 255, 73);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.tcrRefresh.setText("")
        self.tcrRefresh.setObjectName("tcrRefresh")
        self.tcrresult = QtWidgets.QTableWidget(self.tcr_page)
        self.tcrresult.setGeometry(QtCore.QRect(20, 120, 521, 581))
        self.tcrresult.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tcrresult.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tcrresult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tcrresult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tcrresult.setRowCount(0)
        self.tcrresult.setObjectName("tcrresult")
        self.tcrresult.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tcrresult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tcrresult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tcrresult.setHorizontalHeaderItem(2, item)
        self.TcrExport = QtWidgets.QPushButton(self.tcr_page)
        self.TcrExport.setGeometry(QtCore.QRect(920, 30, 61, 61))
        self.TcrExport.setStyleSheet("QWidget{\n"
"    border-image: url(:/icons/icons/save.png);\n"
"background-color:rgb(92, 233, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.TcrExport.setText("")
        self.TcrExport.setObjectName("TcrExport")
        self.tcr_result_back_2 = QtWidgets.QLabel(self.tcr_page)
        self.tcr_result_back_2.setGeometry(QtCore.QRect(10, 110, 541, 601))
        self.tcr_result_back_2.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius:20px;")
        self.tcr_result_back_2.setText("")
        self.tcr_result_back_2.setObjectName("tcr_result_back_2")
        self.tcr_tcr_folderbtn = QtWidgets.QPushButton(self.tcr_page)
        self.tcr_tcr_folderbtn.setGeometry(QtCore.QRect(730, 30, 61, 61))
        self.tcr_tcr_folderbtn.setStyleSheet("QPushButton{\n"
"image: url(:/icons/icons/folder.png);\n"
"background-color: rgb(255, 242, 64);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.tcr_tcr_folderbtn.setText("")
        self.tcr_tcr_folderbtn.setObjectName("tcr_tcr_folderbtn")
        self.tcr_hla_folderbtn = QtWidgets.QPushButton(self.tcr_page)
        self.tcr_hla_folderbtn.setGeometry(QtCore.QRect(340, 30, 61, 61))
        self.tcr_hla_folderbtn.setStyleSheet("QPushButton{\n"
"image: url(:/icons/icons/folder.png);\n"
"background-color: rgb(255, 242, 64);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.tcr_hla_folderbtn.setText("")
        self.tcr_hla_folderbtn.setObjectName("tcr_hla_folderbtn")
        self.tcr_append = QtWidgets.QCheckBox(self.tcr_page)
        self.tcr_append.setGeometry(QtCore.QRect(840, 90, 81, 19))
        self.tcr_append.setObjectName("tcr_append")
        self.tcrprogress = QtWidgets.QProgressBar(self.tcr_page)
        self.tcrprogress.setGeometry(QtCore.QRect(0, 710, 1081, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tcrprogress.sizePolicy().hasHeightForWidth())
        self.tcrprogress.setSizePolicy(sizePolicy)
        self.tcrprogress.setMaximumSize(QtCore.QSize(16777215, 21))
        self.tcrprogress.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255,0);")
        self.tcrprogress.setProperty("value", 0)
        self.tcrprogress.setObjectName("tcrprogress")
        self.tcr_result_back_2.raise_()
        self.inputHLA2.raise_()
        self.inputTcr.raise_()
        self.predictTcr.raise_()
        self.tcrGraphArea.raise_()
        self.tcrRefresh.raise_()
        self.tcrresult.raise_()
        self.TcrExport.raise_()
        self.tcr_tcr_folderbtn.raise_()
        self.tcr_hla_folderbtn.raise_()
        self.tcr_append.raise_()
        self.tcrprogress.raise_()
        self.stackedWidget.addWidget(self.tcr_page)
        self.aomp_page = QtWidgets.QWidget()
        self.aomp_page.setStyleSheet("background-color:rgb(117, 139, 173);\n"
"\n"
"border-radius:20px;")
        self.aomp_page.setObjectName("aomp_page")
        self.inputHLA3 = QtWidgets.QLineEdit(self.aomp_page)
        self.inputHLA3.setGeometry(QtCore.QRect(30, 20, 341, 61))
        self.inputHLA3.setStyleSheet("QLineEdit{\n"
"background-color: rgba(255, 255, 255,150);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgb(0,0,0);\n"
"font: 25 16pt \"Bahnschrift Light\";\n"
"}\n"
"")
        self.inputHLA3.setObjectName("inputHLA3")
        self.inputPeptide2 = QtWidgets.QLineEdit(self.aomp_page)
        self.inputPeptide2.setGeometry(QtCore.QRect(430, 20, 351, 61))
        self.inputPeptide2.setStyleSheet("QLineEdit{\n"
"background-color: rgba(255, 255, 255,150);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgb(0,0,0);\n"
"font: 25 16pt \"Bahnschrift Light\";\n"
"}")
        self.inputPeptide2.setObjectName("inputPeptide2")
        self.AompExport = QtWidgets.QPushButton(self.aomp_page)
        self.AompExport.setGeometry(QtCore.QRect(910, 20, 61, 61))
        self.AompExport.setStyleSheet("QWidget{\n"
"    border-image: url(:/icons/icons/save.png);\n"
"\n"
"background-color:rgb(92, 233, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.AompExport.setText("")
        self.AompExport.setObjectName("AompExport")
        self.predictAomp = QtWidgets.QPushButton(self.aomp_page)
        self.predictAomp.setGeometry(QtCore.QRect(830, 20, 61, 61))
        self.predictAomp.setStyleSheet("QWidget{\n"
"border-image: url(:/icons/icons/analysis.png);\n"
"background-color: rgb(255, 154, 114);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.predictAomp.setText("")
        self.predictAomp.setObjectName("predictAomp")
        self.AompRefresh = QtWidgets.QPushButton(self.aomp_page)
        self.AompRefresh.setGeometry(QtCore.QRect(990, 20, 61, 61))
        self.AompRefresh.setStyleSheet("QWidget{\n"
"    border-image:url(:/icons/icons/清除_clear.png);\n"
"background-color: rgb(161, 255, 73);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(106, 106, 106);\n"
"}")
        self.AompRefresh.setText("")
        self.AompRefresh.setObjectName("AompRefresh")
        self.aompResult = QtWidgets.QTableWidget(self.aomp_page)
        self.aompResult.setGeometry(QtCore.QRect(20, 110, 1041, 221))
        self.aompResult.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.aompResult.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.aompResult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.aompResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.aompResult.setObjectName("aompResult")
        self.aompResult.setColumnCount(8)
        self.aompResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.aompResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.aompResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.aompResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.aompResult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.aompResult.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.aompResult.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.aompResult.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.aompResult.setHorizontalHeaderItem(7, item)
        self.aompResult.verticalHeader().setDefaultSectionSize(30)
        self.aompResult.verticalHeader().setMinimumSectionSize(30)
        self.aompGraphArea = QtWidgets.QScrollArea(self.aomp_page)
        self.aompGraphArea.setGeometry(QtCore.QRect(10, 340, 631, 371))
        self.aompGraphArea.setStyleSheet("background-color: rgba(27, 53, 113,255);\n"
"border-radius:20px;")
        self.aompGraphArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.aompGraphArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.aompGraphArea.setWidgetResizable(True)
        self.aompGraphArea.setObjectName("aompGraphArea")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 631, 371))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.aompGraphArea.setWidget(self.scrollAreaWidgetContents_7)
        self.aomphistogram = GraphicsLayoutWidget(self.aomp_page)
        self.aomphistogram.setGeometry(QtCore.QRect(659, 340, 411, 371))
        self.aomphistogram.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius:20px;")
        self.aomphistogram.setObjectName("aomphistogram")
        self.aomp_result_back = QtWidgets.QLabel(self.aomp_page)
        self.aomp_result_back.setGeometry(QtCore.QRect(10, 100, 1061, 231))
        self.aomp_result_back.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.aomp_result_back.setText("")
        self.aomp_result_back.setObjectName("aomp_result_back")
        self.aomphistgramback = QtWidgets.QLabel(self.aomp_page)
        self.aomphistgramback.setGeometry(QtCore.QRect(651, 340, 421, 371))
        self.aomphistgramback.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"")
        self.aomphistgramback.setText("")
        self.aomphistgramback.setObjectName("aomphistgramback")
        self.Aompprogress = QtWidgets.QProgressBar(self.aomp_page)
        self.Aompprogress.setGeometry(QtCore.QRect(0, 710, 1081, 20))
        self.Aompprogress.setProperty("value", 0)
        self.Aompprogress.setObjectName("Aompprogress")
        self.aomp_result_back.raise_()
        self.aomphistgramback.raise_()
        self.inputHLA3.raise_()
        self.inputPeptide2.raise_()
        self.AompExport.raise_()
        self.predictAomp.raise_()
        self.AompRefresh.raise_()
        self.aompResult.raise_()
        self.aompGraphArea.raise_()
        self.aomphistogram.raise_()
        self.Aompprogress.raise_()
        self.stackedWidget.addWidget(self.aomp_page)
        self.model_page = QtWidgets.QWidget()
        self.model_page.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.model_page.setObjectName("model_page")
        self.stackedWidget.addWidget(self.model_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.setting_page.setObjectName("setting_page")
        self.stackedWidget.addWidget(self.setting_page)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(40, 50, 71, 631))
        self.frame_4.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 71, 631))
        self.groupBox.setStyleSheet("border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.closebtn = QtWidgets.QPushButton(self.groupBox)
        self.closebtn.setGeometry(QtCore.QRect(10, 520, 51, 51))
        self.closebtn.setStyleSheet("QPushButton{\n"
"    border-image: url(:/icons/icons/开关_power.png);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(159, 159, 159);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(165, 255, 255);\n"
"}\n"
"")
        self.closebtn.setText("")
        self.closebtn.setCheckable(False)
        self.closebtn.setObjectName("closebtn")
        self.writingbtn = QtWidgets.QPushButton(self.groupBox)
        self.writingbtn.setGeometry(QtCore.QRect(10, 420, 51, 51))
        self.writingbtn.setStyleSheet("QPushButton{\n"
"    border-image: url(:/icons/icons/cell.png);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(159, 159, 159);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(165, 255, 255);\n"
"}")
        self.writingbtn.setText("")
        self.writingbtn.setCheckable(False)
        self.writingbtn.setObjectName("writingbtn")
        self.settingbtn = QtWidgets.QPushButton(self.groupBox)
        self.settingbtn.setGeometry(QtCore.QRect(10, 320, 51, 51))
        self.settingbtn.setStyleSheet("QPushButton{\n"
"    \n"
"    border-image: url(:/icons/icons/setting.png);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(159, 159, 159);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(165, 255, 255);\n"
"}")
        self.settingbtn.setText("")
        self.settingbtn.setCheckable(False)
        self.settingbtn.setObjectName("settingbtn")
        self.modelbtn = QtWidgets.QPushButton(self.groupBox)
        self.modelbtn.setGeometry(QtCore.QRect(10, 230, 51, 51))
        self.modelbtn.setStyleSheet("QPushButton{\n"
"    \n"
"    border-image: url(:/icons/icons/smart-optimization.png);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(159, 159, 159);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(165, 255, 255);\n"
"}")
        self.modelbtn.setText("")
        self.modelbtn.setCheckable(False)
        self.modelbtn.setObjectName("modelbtn")
        self.backbtn = QtWidgets.QPushButton(self.groupBox)
        self.backbtn.setGeometry(QtCore.QRect(10, 140, 51, 51))
        self.backbtn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"border-image: url(:/icons/icons/上一步_back.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(159, 159, 159);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(165, 255, 255);\n"
"}")
        self.backbtn.setText("")
        self.backbtn.setCheckable(False)
        self.backbtn.setObjectName("backbtn")
        self.homebtn = QtWidgets.QPushButton(self.groupBox)
        self.homebtn.setGeometry(QtCore.QRect(10, 50, 51, 51))
        self.homebtn.setStyleSheet("QWidget{\n"
"    border-radius:30px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-image: url(:/icons/icons/首页_home.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(159, 159, 159);\n"
"    border: none;\n"
"}    \n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(165, 255, 255);\n"
"}")
        self.homebtn.setText("")
        self.homebtn.setCheckable(False)
        self.homebtn.setChecked(False)
        self.homebtn.setObjectName("homebtn")
        self.shadow = QtWidgets.QLabel(Form)
        self.shadow.setGeometry(QtCore.QRect(120, 40, 1091, 741))
        self.shadow.setStyleSheet("background-color: rgb(26, 73, 159);\n"
"border-radius:20px;")
        self.shadow.setText("")
        self.shadow.setObjectName("shadow")
        self.background.raise_()
        self.shadow.raise_()
        self.stackedWidget.raise_()
        self.frame_4.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        self.closebtn.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Peptide预测"))
        self.label_5.setText(_translate("Form", "验证肽和HLA等位基因之间的亲和力"))
        self.label_3.setText(_translate("Form", "Tcr预测"))
        self.label_6.setText(_translate("Form", "验证TCR和HLA等位基因之间的亲和力"))
        self.label_4.setText(_translate("Form", "Aomp"))
        self.label_7.setText(_translate("Form", "对特定HLA等位基因亲和力较弱的特定源肽寻找高亲和力的突变肽。"))
        self.inputHLA1.setPlaceholderText(_translate("Form", "请输入HLA"))
        self.inputPeptide.setPlaceholderText(_translate("Form", "请输入Peptide"))
        item = self.peptideresult.horizontalHeaderItem(0)
        item.setText(_translate("Form", "HLA"))
        item = self.peptideresult.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Peptide"))
        item = self.peptideresult.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Binding"))
        item = self.peptideresult.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Peptide Score"))
        self.predictPeptide.setToolTip(_translate("Form", "预测"))
        self.predictPeptide.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.peptideExport.setToolTip(_translate("Form", "导出数据"))
        self.peptideRefresh.setToolTip(_translate("Form", "清空"))
        self.peptide_append.setText(_translate("Form", "append"))
        self.inputHLA2.setPlaceholderText(_translate("Form", "请输入Peptide"))
        self.inputTcr.setPlaceholderText(_translate("Form", "请输入TCR"))
        self.predictTcr.setToolTip(_translate("Form", "预测"))
        self.predictTcr.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.tcrRefresh.setToolTip(_translate("Form", "清空"))
        item = self.tcrresult.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Peptide"))
        item = self.tcrresult.horizontalHeaderItem(1)
        item.setText(_translate("Form", "TCR"))
        item = self.tcrresult.horizontalHeaderItem(2)
        item.setText(_translate("Form", "TCR Score"))
        self.TcrExport.setToolTip(_translate("Form", "导出数据"))
        self.tcr_append.setText(_translate("Form", "append"))
        self.inputHLA3.setPlaceholderText(_translate("Form", "请输入HLA"))
        self.inputPeptide2.setPlaceholderText(_translate("Form", "请输入Peptide"))
        self.AompExport.setToolTip(_translate("Form", "导出数据"))
        self.predictAomp.setToolTip(_translate("Form", "预测"))
        self.predictAomp.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.AompRefresh.setToolTip(_translate("Form", "清空"))
        item = self.aompResult.horizontalHeaderItem(0)
        item.setText(_translate("Form", "HLA"))
        item = self.aompResult.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Original Peptide"))
        item = self.aompResult.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Mutated Peptide"))
        item = self.aompResult.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Mutation amino-acid site"))
        item = self.aompResult.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Mutation number"))
        item = self.aompResult.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Sequence similarity"))
        item = self.aompResult.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Binding"))
        item = self.aompResult.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Prediction score"))
from pyqtgraph import GraphicsLayoutWidget
import src_rc
